"use client";

import { useMemo, useState } from "react";
import { Activity, BarChart3, Clock3, Database, Dice5, Flame, Info, RefreshCw, Sparkles, Target, TrendingUp } from "lucide-react";

type View = "overview" | "numbers" | "returns" | "patterns" | "predictions" | "method";
const frequencies=[34,38,38,28,39,28,36,31,31,47,35,47,45,37,34,35,45,25,31,34,41,39,28,45,35,27,31,38,35,43,35,40,38,39,34,27,36,30,22,39];
const recent20=[0,2,2,3,1,1,2,4,1,2,2,2,6,7,4,3,3,2,4,5,4,5,2,4,5,2,2,2,1,3,3,4,4,4,2,0,4,1,2,3];
const recent50=[5,7,7,5,7,4,8,8,4,6,8,11,10,12,8,8,8,6,7,8,9,11,6,10,8,5,7,8,6,10,7,14,7,10,5,3,10,5,5,8];
const droughts=[13,1,1,0,3,16,0,2,9,16,4,13,4,1,3,1,6,13,1,0,4,2,0,3,2,11,0,8,13,11,1,2,0,0,9,22,5,2,1,4];
const returnAvg=[5.68,6.05,6.06,8.58,6.16,7.15,6.90,7.24,7.17,4.84,6.34,4.82,5.19,5.86,6.88,6.23,4.81,8.57,6.41,7.23,5.26,6.27,8.12,5.16,6.51,8.24,7.16,5.36,6.15,4.63,6.28,5.87,5.95,6.00,6.21,7.60,6.47,6.59,9.25,6.03];
const powerball=[27,19,31,18,21,27,16,27,20,32];
const topPairs=[[12,28,14],[3,40,13],[10,22,12],[5,12,12],[10,25,11],[22,24,11],[21,37,11],[17,30,11],[2,30,11]];
const topTriples=[[22,24,34,5],[12,17,28,5],[10,15,22,4],[9,12,15,4],[3,13,40,4],[10,28,33,4]];
const strikeTop=[{n:10,c:36},{n:40,c:32},{n:12,c:31},{n:28,c:31},{n:17,c:30},{n:14,c:30},{n:5,c:29},{n:21,c:29}];
const nav=[{id:"overview",label:"Overview",icon:Activity},{id:"numbers",label:"Number lab",icon:BarChart3},{id:"returns",label:"Return cycles",icon:Clock3},{id:"patterns",label:"Patterns",icon:Sparkles},{id:"predictions",label:"8 sequences",icon:Dice5},{id:"method",label:"Method",icon:Info}] as const;
const numberData=frequencies.map((count,i)=>({number:i+1,count,recent20:recent20[i],recent50:recent50[i],drought:droughts[i],avg:returnAvg[i],z:(count-35.7)/5.51}));
function seeded(seed:number){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
function makeSequences(seed:number){const rand=seeded(seed),used=new Set<string>(),result:{nums:number[];pb:number;style:string}[]=[];const styles=["Momentum","Balanced hot","Long-run strength","Return-cycle mix","Hot + overdue","Pair-aware","Contrarian balance","Diversified"];const profiles=[[.15,.45,.30,.05,.05],[.30,.25,.25,.10,.10],[.55,.10,.20,.05,.10],[.15,.15,.15,.15,.40],[.25,.20,.15,.35,.05],[.35,.25,.20,.10,.10],[.10,.10,.10,.55,.15],[.25,.20,.20,.15,.20]];for(let row=0;row<8;row++){let nums:number[]=[];for(let attempt=0;attempt<30;attempt++){const p=profiles[row];nums=numberData.map(d=>{const long=d.count/47,short=d.recent20/7,medium=d.recent50/14,due=Math.min(d.drought/16,1),stable=1-Math.min(Math.abs(d.avg-6.67)/5,1);return{...d,w:.05+p[0]*long+p[1]*short+p[2]*medium+p[3]*due+p[4]*stable+rand()*.12}}).sort((a,b)=>b.w-a.w).slice(0,6).map(x=>x.number).sort((a,b)=>a-b);const key=nums.join("-");if(!used.has(key)){used.add(key);break}}const pb=powerball.map((c,i)=>({n:i+1,w:c/32+rand()*.45})).sort((a,b)=>b.w-a.w)[row%10].n;result.push({nums,pb,style:styles[row]})}return result}
function Ball({n,tone="plain",small=false}:{n:number;tone?:"plain"|"hot"|"cold"|"pb";small?:boolean}){return <span className={`ball ${tone} ${small?"small":""}`}>{n}</span>}
function Metric({label,value,note,accent}:{label:string;value:string;note:string;accent?:string}){return <article className="metric"><div className="metric-top"><span>{label}</span>{accent&&<i style={{background:accent}}/>}</div><strong>{value}</strong><p>{note}</p></article>}
function SectionHead({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="section-head"><span>{eyebrow}</span><h2>{title}</h2><p>{copy}</p></div>}

export default function Home(){
 const[view,setView]=useState<View>("overview"),[windowSize,setWindowSize]=useState<"all"|"50"|"20">("all"),[sort,setSort]=useState<"hot"|"cold"|"number">("hot"),[seed,setSeed]=useState(20260912);
 const sequences=useMemo(()=>makeSequences(seed),[seed]);const ranked=useMemo(()=>[...numberData].sort((a,b)=>sort==="number"?a.number-b.number:sort==="cold"?a.count-b.count:b.count-a.count),[sort]);const max=windowSize==="all"?47:windowSize==="50"?14:7;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brandmark"><TrendingUp size={20}/></span><div><b>DrawScope</b><small>NZ Lotto Lab</small></div></div><nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><Icon size={18}/><span>{item.label}</span></button>})}</nav><div className="side-note"><Database size={17}/><div><b>238 draws loaded</b><span>2024–9 Sep 2026</span></div></div><p className="sidebar-foot">For statistical exploration only.<br/>Every valid line has equal draw odds.</p></aside>
 <main className="content"><header className="topbar"><h1>{nav.find(n=>n.id===view)?.label}</h1><div className="status"><i/> Dataset verified <span>•</span> Updated 9 Sep 2026</div></header>
 {view==="overview"&&<div className="view"><section className="signal-hero"><div><span className="eyebrow">Statistical signal board</span><h2>Patterns are visible.<br/><em>Randomness still wins.</em></h2><p>Explore frequency, momentum, droughts and return cycles across 238 NZ Lotto draws—without confusing historical patterns with future odds.</p><button onClick={()=>setView("predictions")}>Open 8-sequence model <Dice5 size={18}/></button></div><div className="orbit"><span>Current watchlist</span><div className="orbit-balls">{[14,13,22,32,25].map(n=><Ball key={n} n={n} tone={n<15?"hot":"plain"}/>)}</div><p><b>14</b> leads the last 20 · <b>32</b> leads the last 50</p></div></section><div className="metric-grid"><Metric label="Historical leaders" value="10 · 12" note="47 appearances each" accent="#ff6b35"/><Metric label="Recent leader" value="14" note="7 of the last 20 draws" accent="#7559e8"/><Metric label="Longest drought" value="36" note="22 draws without appearing" accent="#35a9ce"/><Metric label="Uniformity test" value="p = 0.401" note="Compatible with randomness" accent="#2faf84"/></div><section className="panel split"><div><SectionHead eyebrow="Momentum map" title="Long-term strength vs recent form" copy="The strongest crossover is 13; 10 and 12 remain historical leaders but have cooled recently."/><div className="watch-table"><div className="watch-head"><span>Number</span><span>All</span><span>Last 50</span><span>Last 20</span><span>Drought</span></div>{[14,13,22,32,24,37,12,10].map(n=>{const d=numberData[n-1];return <div className="watch-row" key={n}><Ball n={n} small tone={n===14||n===13?"hot":"plain"}/><span>{d.count}</span><span>{d.recent50}</span><span>{d.recent20}</span><span>{d.drought}</span></div>})}</div></div><div className="truth-card"><Target/><span>Fair-draw baseline</span><strong>15%</strong><p>Every individual number has the same chance of appearing among the six main numbers in the next fair draw.</p><div><b>0.915</b><small>actual repeats / draw</small></div><div><b>0.900</b><small>theoretical repeats / draw</small></div></div></section></div>}
 {view==="numbers"&&<div className="view"><SectionHead eyebrow="40-number explorer" title="See every number in context" copy="Switch time windows and sort the complete field. Bar lengths are relative within the selected window."/><div className="toolbar"><div className="segmented">{(["all","50","20"] as const).map(w=><button key={w} onClick={()=>setWindowSize(w)} className={windowSize===w?"active":""}>{w==="all"?"All 238":`Last ${w}`}</button>)}</div><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="hot">Hot → cold</option><option value="cold">Cold → hot</option><option value="number">Number order</option></select></div><section className="number-grid">{ranked.map(d=>{const value=windowSize==="all"?d.count:windowSize==="50"?d.recent50:d.recent20,tone=d.z>=1?"hot":d.z<=-1?"cold":"plain";return <article className="number-card" key={d.number}><div><Ball n={d.number} tone={tone}/><span>{d.z>=2?"super hot":d.z>=1?"hot":d.z<=-2?"super cold":d.z<=-1?"cold":"neutral"}</span></div><strong>{value}<small> hits</small></strong><div className="bar"><i style={{width:`${Math.max(5,value/max*100)}%`}}/></div><footer><span>gap {d.drought}</span><span>avg {d.avg.toFixed(2)}</span></footer></article>})}</section></div>}
 {view==="returns"&&<div className="view"><SectionHead eyebrow="Return-cycle analysis" title="How long does a number take to return?" copy="Observed return intervals vary widely by number, but the spread is normal for random histories of this size."/><div className="metric-grid"><Metric label="Theoretical average" value="6.67 draws" note="Geometric model at 15%"/><Metric label="Fastest observed" value="30 · 4.63" note="Average draw intervals"/><Metric label="Slowest observed" value="39 · 9.25" note="Average draw intervals"/><Metric label="Random simulations" value="47%" note="Produced equal/wider spread"/></div><section className="panel"><h3>Average return interval by number</h3><p className="muted">Lower means the number returned sooner in this sample.</p><div className="return-chart">{[...numberData].sort((a,b)=>a.avg-b.avg).map(d=><div className="return-item" key={d.number}><span>{d.number}</span><div><i style={{height:`${d.avg/9.25*100}%`}}/><b className={d.avg<5.5?"fast":d.avg>8?"slow":""}>{d.avg.toFixed(1)}</b></div></div>)}</div><div className="benchmark"><span/>6.67 theoretical average</div></section><section className="panel two-col"><div><h3>Return-by probability</h3>{[["Next draw","15.25%","15.00%"],["Within 5","57.33%","55.63%"],["Within 10","81.77%","80.31%"],["Within 20","96.02%","96.12%"]].map(x=><div className="prob" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]} expected</small></div>)}</div><div><h3>Longest completed gaps</h3>{[[4,42],[23,42],[38,41],[37,33],[12,31],[5,31]].map(x=><div className="gap" key={x[0]}><Ball n={x[0]} small tone="cold"/><div><i style={{width:`${x[1]/42*100}%`}}/></div><b>{x[1]} draws</b></div>)}</div></section></div>}
 {view==="patterns"&&<div className="view"><SectionHead eyebrow="Co-occurrence lab" title="Pairs, triples and structural patterns" copy="These are the strongest patterns discovered after searching hundreds or thousands of combinations, so multiple-comparison caution matters."/><section className="pattern-grid"><article className="panel"><div className="panel-icon orange"><Flame/></div><h3>Top pairs</h3><p className="muted">Preselected-pair expectation: 4.58 times</p>{topPairs.map(([a,b,c],i)=><div className="combo" key={`${a}-${b}`}><span>{i+1}</span><div><Ball n={a} small/><Ball n={b} small/></div><b>{c}×</b></div>)}</article><article className="panel"><div className="panel-icon violet"><Sparkles/></div><h3>Top triples</h3><p className="muted">Preselected-triple expectation: 0.48 times</p>{topTriples.map(([a,b,c,h],i)=><div className="combo" key={`${a}-${b}-${c}`}><span>{i+1}</span><div><Ball n={a} small/><Ball n={b} small/><Ball n={c} small/></div><b>{h}×</b></div>)}</article><article className="panel"><div className="panel-icon blue"><Dice5/></div><h3>Powerball</h3><p className="muted">Frequency across 238 draws</p><div className="pb-grid">{powerball.map((c,i)=><div key={i}><Ball n={i+1} tone="pb" small/><span>{c}</span></div>)}</div><p className="callout"><b>10 & 3</b> lead historically; <b>9</b> leads the most recent 20.</p></article><article className="panel"><div className="panel-icon green"><Target/></div><h3>Strike leaders</h3><p className="muted">Appearances among the ordered Strike numbers</p>{strikeTop.map(x=><div className="strike" key={x.n}><Ball n={x.n} small/><div><i style={{width:`${x.c/36*100}%`}}/></div><b>{x.c}</b></div>)}</article></section><section className="fact-strip"><div><strong>0</strong><span>exact duplicates</span></div><div><strong>1</strong><span>five-of-six near duplicate</span></div><div><strong>51.3%</strong><span>with consecutive numbers</span></div><div><strong>49.7 / 50.3</strong><span>odd / even split</span></div></section></div>}
 {view==="predictions"&&<div className="view"><div className="prediction-head"><SectionHead eyebrow="Experimental generator" title="Eight modelled sequences" copy="Each line uses a different mix of historical frequency, momentum, drought and return-cycle stability."/><button onClick={()=>setSeed(s=>s+7919)}><RefreshCw size={17}/> Regenerate</button></div><div className="warning"><Info size={18}/><p><b>Important:</b> these are statistically themed selections, not forecasts. Every valid Lotto line has the same mathematical chance of winning. Never spend more because a line receives a stronger historical score.</p></div><section className="sequence-grid">{sequences.map((s,i)=><article className="sequence" key={`${seed}-${i}`}><header><span>Sequence {String(i+1).padStart(2,"0")}</span><em>{s.style}</em></header><div className="sequence-balls">{s.nums.map(n=><Ball key={n} n={n} tone={frequencies[n-1]>=43||recent20[n-1]>=6?"hot":"plain"}/>)}<span className="plus">+</span><Ball n={s.pb} tone="pb"/></div><footer><span>Sum {s.nums.reduce((a,b)=>a+b,0)}</span><span>{s.nums.filter(n=>n%2).length} odd / {s.nums.filter(n=>n%2===0).length} even</span><span>{s.nums.filter(n=>n<=20).length} low / {s.nums.filter(n=>n>20).length} high</span></footer></article>)}</section><section className="panel model-note"><h3>How the generator is balanced</h3><div>{[["#ff6b35","Long-run frequency"],["#7559e8","Last-20 momentum"],["#35a9ce","Last-50 momentum"],["#f0b84c","Current drought"],["#2faf84","Return stability"]].map(x=><span key={x[1]}><i style={{background:x[0]}}/>{x[1]}</span>)}</div><p>The eight profiles intentionally diversify weighting instead of pretending there is one “best” model. Regeneration adds a small seeded variation while preserving each profile’s rules.</p></section></div>}
 {view==="method"&&<div className="view"><SectionHead eyebrow="Methods & data quality" title="What the analysis does—and does not—say" copy="The dashboard describes one historical sample. Past outcomes do not change future probabilities."/><section className="method-grid"><article className="panel"><h3><Database/> Dataset</h3><dl>{[["Total draws","238"],["2024","104"],["2025 selected months","62"],["2026 to 9 Sep","72"]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl><div className="warning compact"><Info size={17}/><p>May–September 2025 is absent. Cross-gap transitions are excluded from return and consecutive-draw calculations.</p></div></article><article className="panel"><h3><Activity/> Statistical tests</h3><dl>{[["Main numbers","p = 0.401"],["Powerball","p = 0.204"],["Strike","p = 0.302"],["Bonus","p = 0.194"]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl><p className="muted">No global test provides convincing evidence of non-uniformity.</p></article><article className="panel wide"><h3><BarChart3/> Benchmarks</h3><div className="benchmark-grid">{[["35.7","expected main-number appearances"],["5.51","expected standard deviation"],["123","theoretical average draw sum"],["121.97","observed average draw sum"],["3,838,380","possible six-number lines"],["780 / 9,880","pairs / triples searched"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></article></section></div>}
 </main></div>
}
